### PR TITLE
Stage 2 catastrophe

### LINKED ISSUE #98: Catastrophe situation for live bonds
catastrophic status allows stakers in stage 3 to refund their stake. we need a similar mechanism for stage 2 bonds

### PR DESCRIPTION
**Pull request by ewansheldon**
- resolves #98 
- prevents new bonds or claiming of rewards when in catastrophe
- ensures there is enough of both assets in contracts to pay out principals, before enabling catastrophe
- corrects spelling of catastrophe in stage 3 😅

### CODE REVIEW

**Review by therealdannzor — APPROVED** [review]
Great 👍

**Comment by simonmorley** [comment]
awkward

**Comment by simonmorley** [comment]
I told everyone that Ewan was judging my spelling

**Comment by ewansheldon** [comment]
so embarrassed i missed this originally

**Pull request merged**
